#pragma once

//Енумерация за указване кои полета да се активират в диалога
enum ENABLE_DIALOG_CONTROLS_FLAG
{
	ENABLE_CONTROLS_FLAG_ALL,
	ENABLE_CONTROLS_FLAG_NONE,
	ENABLE_CONTROLS_FLAG_ONLY_REGION,
	ENABLE_CONTROLS_FLAG_ONLY_NAME
};

//Енумерация за указване на извършена опреция за вюто
enum OPERATIONS_WITH_DATA_FLAGS
{
	LPARAM_INSERT = 1,
	LPARAM_UPDATE = 2,
	LPARAM_DELETE = 3
};

enum DATA_TO_RUN_OPERATION_FLAG
{
	DO_OPERATION_FOR_PERSON_AND_PHONE_NUMBERS_TABLE,
	DO_OPERATION_FOR_ONLY_PERSON_TABLE,
	DO_OPERATION_FOR_ONLY_PHONE_NUMBERS_TABLE
};

