#pragma once

enum DIALOG_CTR_INFO
{
	DIALOG_CTR_INFO_TEXT_BOX_MAX_LENGTH_ENTERED_STRING = 128,
	DIALOG_CTR_INFO_TEXT_BOX_MAX_LENGTH_ENTERED_PHONE_NUMBER = 16,
	DIALOG_CTR_INFO_TEXT_BOX_MAX_LENGTH_ENTERED_EGN = 16
};
