#pragma once

#define LIST_CTR_HEADER_WIDTH 200

//Енумерация за указване на броя колони и тяхната поредност в лист контрола
enum CITIES_LIST_CTR_COLUMN
{
	CITIES_LIST_CTR_COLUMN_REGION = 0,
	CITIES_LIST_CTR_COLUMN_CITY_NAME = 1
};

enum PERSONS_LIST_CTR_COLUMN
{
	PERSONS_LIST_CTR_COLUMN_FIRSTNAME = 1,
	PERSONS_LIST_CTR_COLUMN_LASTNAME = 2,
	PERSONS_LIST_CTR_COLUMN_EGN = 3,
	PERSONS_LIST_CTR_COLUMN_REGION = 4
};

enum PHONE_NUMBERS_LIST_CTR_COLUMN
{
	PHONE_NUMBERS_LIST_CTR_COLUMN_TYPE_PHONE = 1,
	PHONE_NUMBERS_LIST_CTR_COLUMN_PHONE_NUMBER = 2
};