#pragma once

enum ENABLE_DIALOG_CONTROLS_FLAG
{
	ENABLE_CONTROLS_FLAG_ALL,
	ENABLE_CONTROLS_FLAG_NONE,
	ENABLE_CONTROLS_FLAG_ONLY_REGION,
	ENABLE_CONTROLS_FLAG_ONLY_NAME
};

enum OPERATIONS_WITH_DATA_FLAGS
{
	LPARAM_INSERT = 1,
	LPARAM_UPDATE = 2,
	LPARAM_DELETE = 3
};

enum VIEW_LIST_CONTROLA_COUNT_OF_COLUMS
{
	LIST_CONTROL_NUMBER_COLUMN_CITY_NAME = 0,
	LIST_CONTROL_NUMBER_COLUMN_CITY_REGION = 1
};
