#pragma once

//Енумерация за указване кои полета да се активират в диалога
enum ENABLE_DIALOG_CTR_FLAG
{
	ENABLE_DIALOG_CTR_FLAG_ALL,
	ENABLE_DIALOG_CTR_FLAG_NONE,
	ENABLE_DIALOG_CTR_FLAG_ONLY_REGION,
	ENABLE_DIALOG_CTR_FLAG_ONLY_NAME
};

//Енумерация за указване на извършена опреция за вюто
enum OPERATIONS_WITH_DATA_FLAGS
{
	OPERATIONS_WITH_DATA_FLAGS_NOCHANGE,
	OPERATIONS_WITH_DATA_FLAGS_READED,
	OPERATIONS_WITH_DATA_FLAGS_INSERT,
	OPERATIONS_WITH_DATA_FLAGS_UPDATE,
	OPERATIONS_WITH_DATA_FLAGS_DELETE
};

enum FLAG_DO_OPERATION_FOR_TABLE
{
	FLAG_DO_OPERATION_FOR_TABLE_PERSON_AND_PHONE_NUMBERS,
	FLAG_DO_OPERATION_FOR_TABLE_ONLY_PERSON,
	FLAG_DO_OPERATION_FOR_TABLE_ONLY_PHONE_NUMBERS
};

