#pragma once

#define LIST_CTR_COLUMN_WIDTH 200

//Енумерация за указване на броя колони и тяхната поредност в лист контрола
enum CITIES_LIST_CTR_COLUMN
{
	CITIES_LIST_CTR_COLUMN_REGION = 0,
	CITIES_LIST_CTR_COLUMN_CITY_NAME = 1
};

enum PHONE_TYPES_LIST_STR_COLUMN
{
	PHONE_TYPES_LIST_STR_COLUMN_PHONE_TYPE = 0
};

enum PERSONS_LIST_CTR_COLUMN
{
	PERSONS_LIST_CTR_COLUMN_FIRSTNAME = 1,
	PERSONS_LIST_CTR_COLUMN_LASTNAME = 2,
	PERSONS_LIST_CTR_COLUMN_EGN = 3,
	PERSONS_LIST_CTR_COLUMN_REGION = 4
};

enum PHONE_NUMBERS_LIST_CTR_COLUMN
{
	PHONE_NUMBERS_LIST_CTR_COLUMN_TYPE_PHONE = 0,
	PHONE_NUMBERS_LIST_CTR_COLUMN_PHONE_NUMBER = 1
};

#define CITIES_LIST_CTRL_COLUMN_REGION_TITLE _T("Region")
#define CITIES_LIST_CTRL_COLUMN_CITY_TITLE _T("City name")

#define PHONE_TYPES_LIST_CTRL_COLUMN_PHONE_TYPE_TITLE _T("Phone type")

#define PERSONS_LIST_CTRL_COLUMN_FIRSTNAME_TITILE  _T("First name")
#define PERSONS_LIST_CTRL_COLUMN_LASTNAME_TITILE _T("Last name")
#define PERSONS_LIST_CTRL_COLUMN_EGN_TITILE _T("EGN ")
#define PERSONS_LIST_CTRL_COLUMN_REGION_TITILE _T("Region: ")

#define PHONE_NUMBERS_LIST_CTRL_COLUMN_PHONE_TYPE_TITILE _T("Type phone")
#define PHONE_NUMBERS_CTRL_COLUMN_PHONE_NUMBER_TITILE  _T("Phone number")

